name: 'Unlock Secrets'
description: 'Unlocks git-crypt secrets using GPG'
inputs:
  gpg_private_key:
    description: 'GPG Private Key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y git-crypt gnupg

    - name: Import GPG key
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
      run: |
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        echo "use-agent" >> ~/.gnupg/gpg.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        echo "trust-model always" >> ~/.gnupg/gpg.conf
        gpgconf --kill gpg-agent || true
        echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import

    - name: Unlock git-crypt
      shell: bash
      run: git-crypt unlock
